### ISSUE TITLE
Set up ONAP OpenStack environment on Packet for VNF demo

### ISSUE THREAD

**Issue by lixuna** [cncf/cnfs#1]
Goal: Set up ONAP OpenStack environment on Packet for VNF demo
----

## Tasks:

- [x]  Create new VM on Packet or Digital Ocean:
  - [x]  Ubuntu 16.04 
  - [x]  64bit 
  - [x]  125G memory 
  - [x]  1T disk.

- [x]  Clone Gerrit repo => https://gerrit.onap.org/r/p/demo.git , https://github.com/onap/demo/
- [x]  Use Vagrant scripts to run demo scripts

- [x]  Fix issues with Vagrant

- [x]  Fix issues with OpenStack

**Comment by lixuna** [comment]
OpenStack setup is documented in https://github.com/cncf/onap-demo/issues/1

**Comment by lixuna** [comment]
Setting up OpenStack Ocata in Virtualbox on Ubuntu 17.10
---

Provision base dev software and pull down onap-demo code:

```
git clone git@github.com:cncf/onap-demo.git -b amsterdam-openstack-ocata

cd onap-demo

./vagrant/run_demo.sh
```

Deploy the router to new packet server:

```
cd router-node ; vagrant plugin install vagrant-reload ; vagrant up
```

Deploy openstack to new packet server:

```
cd ../vagrant ; vagrant up control ; vagrant up control-1 ; vagrant up control-2
```

Register compute nodes as resources for OpenStack to use:

```
vagrant ssh control -- source /vagrant/openrc \; nova-manage cell_v2 simple_cell_setup
```
