### ISSUE TITLE
Create code to provision and install a minimal VPP as a simple vSwitch

### ISSUE THREAD

**Issue by taylor** [cncf/cnfs#66]
# Create code to provision and install minimal VPP as a simple vSwitch

Goal: Create code that can deploy VPP idempotently on a Ubuntu 18.04+ host

### Tasks

Reference and review:
- [x] Manual setup https://github.com/cncf/cnfs/issues/53
- [x] Review Mike's NSM [Notes for configuring VPP with Mellanox Connectx-4 (PFs and VFs](https://github.com/ligato/networkservicemesh/issues/270#issue-355769450) and use as reference
    * Has Mellanox specific requirements
    * Most recently updated (as of 2018/9/11)
- [x] Review [box-by-box install_vpp_prereqs.sh](https://github.com/cncf/cnfs/blob/master/comparison/box-by-box-kvm-docker/install_vpp_prereqs.sh) and use as reference
- [x] For testing review "[Testing with host virtual interface inside of VPP](https://github.com/cncf/cnfs/issues/61#issuecomment-420458370) and VF trust solution in https://github.com/cncf/cnfs/issues/61#issuecomment-420459167

Host optimization / tuning tasks:
---

- [x] Enable iommu support in grub and reboot system after grub is updated
- [x] Enable huge page support
- [x] Update Mellanox role to support different driver versions from mellanox.com, OS versions needing support: 
  - [x] Ubuntu 16.04+
  - [x] Ubuntu 18.04+

- [x] Enable SR-IOV / VF on the mellanox
   * This can either be on boot with echo to the /proc/sys device, or persistent using
   * /etc/sysctl.conf

- [x] Create role to turn on trust for VF, example
```
ip link set enp94s0f1 vf 1 trust on
ip link set enp94s0f1 vf 0 trust on
```
- Note: device names and number of devices are system dependent

VPP tasks:
---
- [x] Create VPP vSwitch playbook

- [x] Create role for building VPP from source, see https://github.com/cncf/cnfs/issues/61#issuecomment-420459167

- [x] Add support to the VPP role for starting, stopping and restarting the VPP service

- [x] Create role to Enable DPDK for VPP

- [x] Create role to configure VPP as a vSwitch 

- [x] Create working example setup.gate config file for VPP as a vSwitch 
```
create host-interface name enp94s0f4
set interface state host-enp94s0f4 up
set interface ip address host-enp94s0f4 172.16.120.20/24
```

---

### To manually test or debug

System setup
---
- Provision a packet.host on same L2 network as VPP test system created above.  This can be via web ui an Ubuntu 18.04+
- Install arping
- Set an ip on the on L2 interface as 172.16.120.10/24 

Testing example commands:
---
- Run `ping -I enp94s0f4 172.16.120.20` from 2nd host
   * Expected: ICMP responses, no packet loss
- Run `arping -i enp94s0f4 172.16.120.20` from 2nd host
   * Expected: All ARP replies sent and replied to
-  Run `ping -I enp94s0f4 172.16.120.10` from VPP host
   * Expected: ICMP responses, no packet loss
-  Run `arping -i enp94s0f4 172.16.120.10` from VPP host
   * Expected: All ARP replies sent and replied to

**Comment by taylor** [comment]
BLOCKED by https://github.com/cncf/cnfs/issues/67

**Comment by lixuna** [comment]
was blocked by #67 - 67 is completed

**Comment by lixuna** [comment]
Level of effort in pts: 8
---

**Comment by denverwilliams** [comment]
@taylor @michaelspedersen Running into some VPP errors when running on Ubuntu 18.04 system.

```
Nov 09 04:02:48 cnfauto1804 vpp[18970]: /usr/bin/vpp[18970]: clib_elf_parse_file: open `linux-vdso.so.1': No such file or directory
Nov 09 04:02:48 cnfauto1804 /usr/bin/vpp[18970]: clib_elf_parse_file: open `linux-vdso.so.1': No such file or directory
Nov 09 04:02:48 cnfauto1804 vpp[18970]: /usr/bin/vpp[18970]: vlib_thread_init: cpu 32 is not available to be used for the 'workers' thread
Nov 09 04:02:48 cnfauto1804 /usr/bin/vpp[18970]: vlib_thread_init: cpu 32 is not available to be used for the 'workers' thread
Nov 09 04:02:48 cnfauto1804 systemd[1]: vpp.service: Service hold-off time over, scheduling restart.
Nov 09 04:02:48 cnfauto1804 systemd[1]: vpp.service: Scheduled restart job, restart counter is at 5.
Nov 09 04:02:48 cnfauto1804 systemd[1]: Stopped vector packet processing engine.
```
